### ISSUE TITLE
upscaledb-2.2.1 configure: error: cannot find Boost headers version >= 1.53.0

### ISSUE THREAD

**Issue by yut148** [cruppstahl/upscaledb-mysql#1]
To Mr. Christoph Rupp and upscaledb-mysql contributors.
I tried upscaledb-mysql Installation to CentOS7.1　 
(centos-release-7-1.1503.el7.centos.2.8.x86_64)

I tried the following
https://github.com/cruppstahl/upscaledb-mysql/wiki/Installation

git clone https://github.com/cruppstahl/upscaledb.git
cd upscaledb
git checkout topic/2.2.1
sh bootstrap.sh
./configure

However, an configure error occurs
# ./configure --prefix=/usr/local/upscaledb-2.2.1

(omit messeage) 
configure: error: cannot find Boost headers version >= 1.53.0

But boost-devel  is the installation is finished
# rpm -q boost-devel

boost-devel-1.53.0-25.el7.x86_64

Is there a better way.

**Comment by cruppstahl** [comment]
I tried to reproduce this on Centos 7, but everything works as expected.

```
[vagrant@localhost upscaledb]$ hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 6ac46a52b13e40ba8542cda35064f47c
           Boot ID: b22ef8b22e0040808096ded6ae3c208a
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.28.3.el7.x86_64
      Architecture: x86-64

[vagrant@localhost upscaledb]$ rpm -q boost-devel
boost-devel-1.53.0-25.el7.x86_64
```

Can you please attach your `config.log`? It might help us tracking down the problem.

**Comment by yut148** [comment]
Thank you reply.
I tried to install the boost_1_53_0.(from sourcecode)
Then, I turned off the boost_1_53_0.
I had no longer to reproduce later.
Sorry but the log will not send.
Also it sends an issue when there is a problem.
I think this of the issue may be closed.
Thank you very much.

# hostnamectl

   Static hostname: localhost.localdomain
         Icon name: computer
           Chassis: n/a
        Machine ID: 53e189bb74a74b9e920b3a2c3b2ec513
           Boot ID: b2edbe8f056141939780f50f6e1f9950
    Virtualization: oracle
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-229.el7.x86_64
      Architecture: x86_64

**Comment by yut148** [comment]
Get errors running again.
Do you know the cause?

 # hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b28a065c6d584818a068526f1f499271
           Boot ID: 1da4f457072b48e2bb4f5538a5c6cca2
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64

 # rpm -qa | sort | grep boost
boost-1.53.0-25.el7.x86_64
boost-atomic-1.53.0-25.el7.x86_64
boost-chrono-1.53.0-25.el7.x86_64
boost-context-1.53.0-25.el7.x86_64
boost-date-time-1.53.0-25.el7.x86_64
boost-devel-1.53.0-25.el7.x86_64
boost-filesystem-1.53.0-25.el7.x86_64
boost-graph-1.53.0-25.el7.x86_64
boost-iostreams-1.53.0-25.el7.x86_64
boost-locale-1.53.0-25.el7.x86_64
boost-math-1.53.0-25.el7.x86_64
boost-program-options-1.53.0-25.el7.x86_64
boost-python-1.53.0-25.el7.x86_64
boost-random-1.53.0-25.el7.x86_64
boost-regex-1.53.0-25.el7.x86_64
boost-serialization-1.53.0-25.el7.x86_64
boost-signals-1.53.0-25.el7.x86_64
boost-system-1.53.0-25.el7.x86_64
boost-test-1.53.0-25.el7.x86_64
boost-thread-1.53.0-25.el7.x86_64
boost-timer-1.53.0-25.el7.x86_64
boost-wave-1.53.0-25.el7.x86_64

[config.log.txt](https://github.com/cruppstahl/upscaledb-mysql/files/513658/config.log.txt)

**Comment by cruppstahl** [comment]
Did you check out branch `topic/2.2.1`?
Also, do you have g++ installed?

configure:4688: checking for C++ compiler version
configure:4697: g++ --version >&5
./configure: line 4699: g++: command not found
configure:4708: $? = 127
configure:4697: g++ -v >&5
./configure: line 4699: g++: command not found
configure:4708: $? = 127
configure:4697: g++ -V >&5
./configure: line 4699: g++: command not found
configure:4708: $? = 127
configure:4697: g++ -qversion >&5
./configure: line 4699: g++: command not found
configure:4708: $? = 127
configure:4712: checking whether we are using the GNU C++ compiler
configure:4731: g++ -c -O3 -DNDEBUG  conftest.cpp >&5
./configure: line 1639: g++: command not found

**Comment by yut148** [comment]
I made a mistake.
Thank you very much.
Probably the gcc ++ was insufficient.
Now, so you may want to close.

 # Configuring upscaledb version 2.2.0
 # Settings: (encryption) (libcrypto missing - encryption disabled) (ssl-devel missing - encryption disabled) (no zlib) (no snappy) (simd-sse4) (simd-sse2) (no java) (protobuf missing - remote disabled)
 #
 # The remote functionality is disabled because you specified
 # --disable-remote or because of missing dependencies!
 #
 # The Java API is not built because you specified
 # --disable-java or because $JDK is not set
 # Recommendation: install google's performance tools to increase performance
 #================================================================

**Comment by cruppstahl** [comment]
Please make sure that you build the branch `topic/2.2.1`, not master or topic/2.2.0. The mysql storage engine will only work with topic/2.2.1!

**Comment by yut148** [comment]
I agree.
But branch 2.2.1
Well I do not know.
 # git branch -v
  master      a3f58ef issue #82: fixed MacOS compilation problems w/ isset
- topic/2.2.1 d5defc3 Replaced another isset macro

**Comment by cruppstahl** [comment]
Please run the following code:

```
git clone https://github.com/cruppstahl/upscaledb.git
cd upscaledb
git checkout topic/2.2.1
sh bootstrap.sh
./configure
make -j 5 && sudo make install
```

See https://github.com/cruppstahl/upscaledb-mysql/wiki/Installation for more information.

**Comment by yut148** [comment]
Thank you for following me.
Certainly installation is possible.
But the version number is displayed as 2.2.0.
It has changed the only destination.
./configure --prefix=/usr/local/upscaledb-2.2.1 && make -j 5 && sudo make install

 # /usr/local/upscaledb-2.2.1/bin/ups_dump -h
upscaledb 2.2.0 - Copyright (C) 2005-2016 Christoph Rupp (chris@crupp.de).

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

usage: ups_dump [-db DBNAME] [-key FMT] [-maxkey N] [-rec FMT] [-maxrec N] file
usage: ups_dump -h
     -h:     this help screen (alias: --help)
     -db DBNAME: only dump this database (alias: --dbname=<arg>)
     -maxkey N:  limit key length to N bytes (alias: --max-key-size=<arg>)
     -rec FMT:   specify format of the record ('string', 'binary' (default),                   'numeric') (alias: --record-format=<arg>)
     -maxrec N:  limit record length to N bytes (alias: --max-rec-size=<arg>)

[root@localhost upscaledb]# git branch -v
  master      a3f58ef issue #82: fixed MacOS compilation problems w/ isset
- topic/2.2.1 d5defc3 Replaced another isset macro

**Comment by cruppstahl** [comment]
Then maybe you have to use `git checkout origin/topic/2.2.1`.

```
$ git branch -v
* topic/2.2.1  0b72fe0 Minor fixes for 'make dist'
```

The output of `ups_dump` is ok - i have not yet updated its version. Thanks for the pointer.

**Comment by yut148** [comment]
Maybe it remains 2.2.0
Version display is not correct?

# git checkout origin/topic/2.2.1

Checking out files: 100% (254/254), done.
Note: checking out 'origin/topic/2.2.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at d5defc3... Replaced another isset macro
[root@localhost upscaledb]# git branch -v
- (detached from origin/topic/2.2.1) d5defc3 Replaced another isset macro
  master                             a3f58ef issue #82: fixed MacOS compilation problems w/ isset

[root@localhost upscaledb]# sh bootstrap.sh && ./configure --prefix=/usr/local/upscaledb-2.2.1 && make -j 5 && sudo make install && date

[root@localhost upscaledb]#  /usr/local/upscaledb-2.2.1/bin/ups_info -h
upscaledb 2.2.0 - Copyright (C) 2005-2016 Christoph Rupp (chris@crupp.de).

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

usage: ups_info [-db DBNAME] [-f] file
usage: ups_info -h
     -h:     this help screen (alias: --help)
     -db DBNAME: only print info about this database (alias: --dbname=<arg>)
     -b:     print btree information (for developers)(alias: --btree)
     -f:     print full information (alias: --full)

**Comment by cruppstahl** [comment]
I updated the `topic/2.2.1` branch. please pull again, or download via github (https://github.com/cruppstahl/upscaledb/archive/topic/2.2.1.zip).

The latest commit is this one: 

commit 6cc9751fd89530cb06ec2b8e0b3da2ed17843c69
Author: Christoph Rupp chris@crupp.de
Date:   Thu Oct 6 21:33:40 2016 +0200

```
Version bump to 2.2.1
```

Also, ups_dump et al will now print version 2.2.1.

**Comment by yut148** [comment]
Sorry gone over time.
Thank you for sending the zip.
But this is a what?
Seems like not end configure.
this messeage.
It is executed many times.
Please send the correct ones.

 # --disable-java or because $JDK is not set
 # Recommendation: install google's performance tools to increase performance
 #================================================================
 /bin/sh ./config.status

**Comment by cruppstahl** [comment]
I created a Centos7 VM and tested the compilation. I ran into errors because centos distributes an older version of protocol buffers. I already pushed a fix to github. Please delete the 2.2.1.zip file that you downloaded previously, and download the newest version. The following commands worked for me:

```
sudo yum install -y protobuf-compiler protobuf-devel
mkdir tmp
cd tmp
wget https://github.com/cruppstahl/upscaledb/archive/topic/2.2.1.zip
unzip 2.2.1
cd upscaledb-topic-2.2.1
sh bootstrap.sh
./configure
make
sudo make install
```

**Comment by yut148** [comment]
Thank you to check with the Centos7 VM.
I also was confirmed, but this is not a problem.
The following file has been created.
maybe OK.
But not yet, upscaled mysql tried.
I want to hear also in that of the following problems.
Nice to meet you.
https://github.com/cruppstahl/upscaledb-mysql/issues/2

 # ls -al /usr/local/bin/
total 6472
drwxr-xr-x.  2 root root      70 Oct 10 04:27 .
drwxr-xr-x. 17 root root    4096 Oct 10 03:03 ..
-rwxr-xr-x   1 root root 6559834 Oct 10 04:27 ups_bench
-rwxr-xr-x   1 root root   19110 Oct 10 04:27 ups_dump
-rwxr-xr-x   1 root root   23350 Oct 10 04:27 ups_info
-rwxr-xr-x   1 root root   14187 Oct 10 04:27 ups_recover
 # ls -al /usr/local/include/ups/
total 160
drwxr-xr-x  2 root root    141 Oct 10 04:27 .
drwxr-xr-x. 3 root root     16 Oct 10 04:27 ..
-rw-r--r--  1 root root   8101 Oct 10 04:27 msstdint.h
-rw-r--r--  1 root root   3265 Oct 10 04:27 types.h
-rw-r--r--  1 root root 100051 Oct 10 04:27 upscaledb.h
-rw-r--r--  1 root root  18075 Oct 10 04:27 upscaledb.hpp
-rw-r--r--  1 root root  11807 Oct 10 04:27 upscaledb_int.h
-rw-r--r--  1 root root   3791 Oct 10 04:27 upscaledb_srv.h
-rw-r--r--  1 root root  11991 Oct 10 04:27 upscaledb_uqi.h
 # ls -al /usr/local/lib  
total 25596
drwxr-xr-x.  2 root root     4096 Oct 10 04:27 .
drwxr-xr-x. 17 root root     4096 Oct 10 03:03 ..
-rw-r--r--   1 root root 16767948 Oct 10 04:27 libupscaledb.a
-rwxr-xr-x   1 root root     1015 Oct 10 04:27 libupscaledb.la
lrwxrwxrwx   1 root root       21 Oct 10 04:27 libupscaledb.so -> libupscaledb.so.0.1.0
lrwxrwxrwx   1 root root       21 Oct 10 04:27 libupscaledb.so.0 -> libupscaledb.so.0.1.0
-rwxr-xr-x   1 root root  9426737 Oct 10 04:27 libupscaledb.so.0.1.0

 # hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b28a065c6d584818a068526f1f499271
           Boot ID: 90a1569713b34c0fa015b9de01e0dcf6
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64

**Comment by cruppstahl** [comment]
No problem. Please refer to https://github.com/cruppstahl/upscaledb-mysql/wiki/Installation on how to install upscaledb-mysql. Feel free to open an issue or send a mail if you have problems.
